### ISSUE TITLE
0.1.0 fails to compile - parse error with pulp 8.2.1 and psc 0.8.5.0

### ISSUE THREAD

**Issue by dfithian** [joneshf/purescript-algebra#1]
```
Error 1 of 4:

  at /Users/dan/simspace/git/warden/shared/purs/bower_components/purescript-algebra/src/Data/Semilattice.purs line 13, column 5 - line 13, column 5

    Unable to parse module:
    unexpected "function booleanOr(b1) {  return function(b2) {    return b1 || b2;  };}"
    expecting ::


  See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information,
  or to contribute content related to this error.
```

Here's the code:

``` purescript
  instance joinSemilatticeBoolean :: JoinSemilattice Boolean where
    (\/) = booleanOr

  foreign import booleanOr
    "function booleanOr(b1) {\
    \  return function(b2) {\
    \    return b1 || b2;\
    \  };\
    \}" :: Boolean -> Boolean -> Boolean
```

I am new to PureScript but from reading docs it looks like foreign imports need to be defined in a javascript file.

**Comment by joneshf** [comment]
Correct, this code won't compile with the newer compilers.

Note that the last commit is years old at this point. And given that a few other hierarchies have sprung up over the years, I'm not sure if this library has a purpose anymore.

I'll debate updating this for a while—though most likely I'm not going to update it. If you'd like to learn more about ps by updating this library I will gladly help and take a PR though.

**Comment by dfithian** [comment]
Hah, well given that it's taken me almost a week to respond, I may or may not take you up on that, but I would love to when I have a little time!
